// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        878,
				FirstName: "distinctio",
				LastName:  "non",
				Email:     "provident_sit_impedit@Livetube.edu",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        882,
				FirstName: "labore",
				LastName:  "iste",
				Email:     "qBurke@Twitterbeat.name",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        999,
				FirstName: "rem",
				LastName:  "et",
				Email:     "rerum_fugit_est@Jaxworks.org",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        652,
				FirstName: "sint",
				LastName:  "nihil",
				Email:     "zGomez@Yacero.mil",
				Visible:   true,
			},
		}
	return res, nil
}
