// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUser) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        923,
				FirstName: "ea",
				LastName:  "fugit",
				Email:     "KathleenRamos@Quamba.mil",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        369,
				FirstName: "corrupti",
				LastName:  "eum",
				Email:     "nGutierrez@Trudoo.biz",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        5,
				FirstName: "impedit",
				LastName:  "excepturi",
				Email:     "tempora_ullam@Thoughtbridge.gov",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        647,
				FirstName: "quam",
				LastName:  "eum",
				Email:     "1Boyd@Plambee.edu",
				Visible:   true,
			},
		}
	return res, nil
}
